# Cancel 
name: cancel_previous
on: [push]
jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: >-
            1771730,
            2111945,
            2330763,
            2025925,
            1771732,
            1771733,
            2393802,
            1771734,
            1771735,
            1771736,
            2063778,
            2024659,
            2057970,
            1771737
          all_but_latest: true